// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReGuestSiteGreator.Infrastructure.Data;

#nullable disable

namespace ReGuestSiteGreator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311114246_ReorderUsernameColumnInUsers")]
    partial class ReorderUsernameColumnInUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultData = "{}",
                            Meta = "{}",
                            Name = "Header",
                            Script = "",
                            Style = "",
                            Template = "<p>Header</p>",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultData = "{}",
                            Meta = "{}",
                            Name = "Block Footer",
                            Script = "",
                            Style = "",
                            Template = "<p>Block Footer</p>",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultData = "{}",
                            Meta = "{}",
                            Name = "Block 1",
                            Script = "",
                            Style = "",
                            Template = "<p>Block 1</p>",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultData = "{}",
                            Meta = "{}",
                            Name = "Block 2",
                            Script = "",
                            Style = "",
                            Template = "<p>Block 2</p>",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultData = "{}",
                            Meta = "{}",
                            Name = "Block 3",
                            Script = "",
                            Style = "",
                            Template = "<p>Block 3</p>",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultData = "{}",
                            Meta = "{}",
                            Name = "Block 4",
                            Script = "",
                            Style = "",
                            Template = "<p>Block 4</p>",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHomePage")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParentSlug")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SitemapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SitemapId", "Slug")
                        .IsUnique();

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Content = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsHomePage = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            Name = "Home",
                            SitemapId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Slug = "home",
                            SortOrder = 1,
                            Status = 0,
                            Title = "Home",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Content = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsHomePage = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            Name = "Contact Us",
                            SitemapId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Slug = "contact-us",
                            SortOrder = 2,
                            Status = 0,
                            Title = "Contact Us",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Content = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsHomePage = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            Name = "Home",
                            SitemapId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Slug = "home",
                            SortOrder = 1,
                            Status = 0,
                            Title = "Home",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Content = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsHomePage = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            Name = "Contact Us",
                            SitemapId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Slug = "contact-us",
                            SortOrder = 2,
                            Status = 0,
                            Title = "Contact Us",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Content = "",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsHomePage = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            Name = "FAQ",
                            SitemapId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Slug = "faq",
                            SortOrder = 3,
                            Status = 0,
                            Title = "FAQ",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.PageBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("PageId", "BlockId");

                    b.ToTable("PageBlocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000001"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000001"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000001"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000002"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000002"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000002"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000003"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000003"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000005"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000003"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000010"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000003"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000011"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000004"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000012"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000004"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000013"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000004"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000014"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000005"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000015"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000006"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000005"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000016"),
                            BlockId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PageId = new Guid("40000000-0000-0000-0000-000000000005"),
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic plan with essential features for small websites.",
                            Name = "Basic",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Business plan with extended features for growing companies.",
                            Name = "Business",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium plan with all features and priority support.",
                            Name = "Premium",
                            Type = 2
                        });
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Sitemap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Sitemaps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            Name = "Basic Sitemap",
                            PlanId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            Name = "Premium Sitemap",
                            PlanId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@reguestsitecreator.com",
                            PasswordHash = "$2a$11$2C9OxE9D5fdKyYoqDdG45.sGzq99vvqVjZ3Tey3cUCn0tKyZZppQC",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@reguestsitecreator.com",
                            PasswordHash = "$2a$11$VaYCYAUH0DMR3GwWU0D1HOazM8lv/z0XcE/r1ROlP9euDOhqYumvS",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin2"
                        });
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Page", b =>
                {
                    b.HasOne("ReGuestSiteGreator.Domain.Entities.Sitemap", "Sitemap")
                        .WithMany("Pages")
                        .HasForeignKey("SitemapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sitemap");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.PageBlock", b =>
                {
                    b.HasOne("ReGuestSiteGreator.Domain.Entities.Block", "Block")
                        .WithMany("PageBlocks")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReGuestSiteGreator.Domain.Entities.Page", "Page")
                        .WithMany("PageBlocks")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Partner", b =>
                {
                    b.HasOne("ReGuestSiteGreator.Domain.Entities.Plan", "Plan")
                        .WithMany("Partners")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReGuestSiteGreator.Domain.Entities.User", "User")
                        .WithOne("Partner")
                        .HasForeignKey("ReGuestSiteGreator.Domain.Entities.Partner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Sitemap", b =>
                {
                    b.HasOne("ReGuestSiteGreator.Domain.Entities.Plan", "Plan")
                        .WithMany("Sitemaps")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Block", b =>
                {
                    b.Navigation("PageBlocks");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Page", b =>
                {
                    b.Navigation("PageBlocks");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Partners");

                    b.Navigation("Sitemaps");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.Sitemap", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("ReGuestSiteGreator.Domain.Entities.User", b =>
                {
                    b.Navigation("Partner");
                });
#pragma warning restore 612, 618
        }
    }
}
